### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by mangoozt** [mangoozt/usv-testing-service#1]
В порядке снижения приоритетности:
* ! Возможность для каждого сценария генерировать папки с входными данными для usv 
* Сохранение графиков в виде картинки
* Возможность сравнивать разные тесты (сколько стало лучше, хуже и пр.) динамика, короче

В остальном, думаю, я сам сделаю то, что понадобится ))

**Comment by Dostoyewski** [comment]
@mangoozt как ты видишь сравнение? Таблица?

**Comment by Dostoyewski** [comment]
Или же какой-нибудь график?

**Comment by Dostoyewski** [comment]
У меня просто пока идей нет.

**Comment by mangoozt** [comment]
таблица, наверное

**Comment by Dostoyewski** [comment]
Типа решенный сценарий в таком-то коммите?

**Comment by mangoozt** [comment]
тип по сравнению с прошлым стало лучше/хуже на вот столько.

**Comment by mangoozt** [comment]
самое важное -- это формирование папки с файлами

**Comment by Dostoyewski** [comment]
Тупо сохранение файлов в какую-нибудь дефолтную папку?

**Comment by mangoozt** [comment]
например так
